/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ms_toollib_MsToollib */

#ifndef _Included_ms_toollib_MsToollib
#define _Included_ms_toollib_MsToollib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ms_toollib_MsToollib
 * Method:    cal3BV
 * Signature: ([[I)I
 */
JNIEXPORT jint JNICALL Java_ms_1toollib_MsToollib_cal3BV
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     ms_toollib_MsToollib
 * Method:    calZini
 * Signature: ([[I)I
 */
JNIEXPORT jint JNICALL Java_ms_1toollib_MsToollib_calZini
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     ms_toollib_MsToollib
 * Method:    calHzini
 * Signature: ([[I)I
 */
JNIEXPORT jint JNICALL Java_ms_1toollib_MsToollib_calHzini
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     ms_toollib_MsToollib
 * Method:    calRzini
 * Signature: ([[II)I
 */
JNIEXPORT jint JNICALL Java_ms_1toollib_MsToollib_calRzini
  (JNIEnv *, jclass, jobjectArray, jint);

/*
 * Class:     ms_toollib_MsToollib
 * Method:    calIsl
 * Signature: ([[I)I
 */
JNIEXPORT jint JNICALL Java_ms_1toollib_MsToollib_calIsl
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     ms_toollib_MsToollib
 * Method:    calOp
 * Signature: ([[I)I
 */
JNIEXPORT jint JNICALL Java_ms_1toollib_MsToollib_calOp
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     ms_toollib_MsToollib
 * Method:    laymine
 * Signature: (IIIII)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_ms_1toollib_MsToollib_laymine
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     ms_toollib_MsToollib
 * Method:    calProbabilityOnboard
 * Signature: ([[ID)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ms_1toollib_MsToollib_calProbabilityOnboard
  (JNIEnv *, jclass, jobjectArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
