name: npm_CI

on:
  push:
    tags: ['*']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install wasm-pack
      - run: wasm-pack build --out-dir pkg
        working-directory: wasm
        env:
          RUSTFLAGS: ""
      - run: npm publish --access public
        working-directory: wasm/pkg
        env:
          NODE_AUTH_TOKEN: ""
      - run: wasm-pack build --target nodejs --out-dir pkg-nodejs
        working-directory: wasm
        env:
          RUSTFLAGS: ""
      - run: |
          jq '.version += "-alpha"' package.json > tmp.json && mv tmp.json package.json
          npm publish --tag alpha
        working-directory: wasm/pkg-nodejs