
name: npm_CI

on:
  push:
    tags: ["*"]

jobs:
  publish:
    permissions:
      id-token: write   # 必须，让 OIDC 工作
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetli/wasm-pack-action@v0.4
      - run: wasm-pack build --out-dir pkg
      - run: cd pkg && npm publish --provenance --access public
      - run: wasm-pack build --target nodejs --out-dir pkg-nodejs
      - run: |
          cd pkg-nodejs
          jq '.version += "-alpha"' package.json > tmp.json && mv tmp.json package.json
          npm publish --tag alpha